vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        message_attachment:
            uri_prefix: /attachment
            upload_destination: '%kernel.project_dir%/public/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer